import org.apache.bcel.generic.Select;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.junit.Test;

public class NewTours {
	static WebDriver driver;
	@Test
	public void testRegisterNew() throws InterruptedException {
		System.setProperty("webdriver.gecko.driver",
				"C:\\Users\\Administrator\\Desktop\\Selenium\\Selenium\\chromedriver.exe");
		driver = new FirefoxDriver();
		driver.get("http://newtours.demoaut.com/index.php");
		WebElement registerBt = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/a"));
		registerBt.click();
		Thread.sleep(500);
		final String userName = "flatulentwalrus";
		final String password = "Pa55w0rd";
		final String firstName = "Amanda";
		final String lastName = "Hugankiss";
		final String phone = "07123456798";
		final String email = "notarealeamil@fakeaddress.com";
		final String address1 = "123 Fake Street";
		final String address2 = "Not A Real Place";
		final String city = "Nowhere";
		final String state = "texas";
		final String postCode = "#FFFFFF";
		final String cardNumber = "213453752182903";
		WebElement firstNameTb = driver.findElement(By.name("firstName"));
		firstNameTb.sendKeys(firstName);
		WebElement lastNameTb = driver.findElement(By.name("lastName"));
		lastNameTb.sendKeys(lastName);
		WebElement phoneTb = driver.findElement(By.name("phone"));
		phoneTb.sendKeys(phone);
		WebElement emailTb = driver.findElement(By.name("userName")); //they are just testing me, right?
		emailTb.sendKeys(email);
		WebElement address1Tb = driver.findElement(By.name("address1"));
		address1Tb.sendKeys(address1);
		WebElement address2Tb = driver.findElement(By.name("address2")); 
		address2Tb.sendKeys(address2);
		WebElement cityTb = driver.findElement(By.name("city")); 
		cityTb.sendKeys(city);
		WebElement stateTb = driver.findElement(By.name("state"));
		stateTb.sendKeys(state);
		WebElement postalCodeTb = driver.findElement(By.name("postalCode"));
		postalCodeTb.sendKeys(postCode);
		WebElement usernameTb = driver.findElement(By.name("email")); //no really
		usernameTb.sendKeys(userName);
		WebElement passwordTb = driver.findElement(By.name("password"));
		passwordTb.sendKeys(password);
		WebElement passwordConfirmTb = driver.findElement(By.name("confirmPassword"));
		passwordConfirmTb.sendKeys(password);
		WebElement submitBt = driver.findElement(By.name("register"));
		Thread.sleep(500);
		submitBt.click();
		Thread.sleep(500);
		WebElement signInBt = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[3]/td/p[2]/font/a[1]"));
		signInBt.click();
		Thread.sleep(500);
		usernameTb = driver.findElement(By.name("userName")); //correctly named here
		usernameTb.sendKeys(userName);
		passwordTb = driver.findElement(By.name("password"));
		passwordTb.sendKeys(password);
		submitBt = driver.findElement(By.name("login"));
		submitBt.click();
		Thread.sleep(500);
		WebElement oneWayRaBt = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[2]/td[2]/b/font/input[2]"));
		oneWayRaBt.click(); 
		WebElement departFromDDB = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[4]/td[2]/select/option[3]"));
		departFromDDB.click();
		WebElement arriveAtDDB = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[6]/td[2]/select/option[4]"));
		arriveAtDDB.click();
		WebElement returnMonthDDB = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[7]/td[2]/select[1]/option[10]"));
		returnMonthDDB.click();
		WebElement firstClassRaBt = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[9]/td[2]/font/font/input[2]"));
		firstClassRaBt.click();
		WebElement airlineDDB = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[10]/td[2]/select/option[2]"));
		airlineDDB.click(); 
		Thread.sleep(500);
		WebElement findFlightsBt = driver.findElement(By.name("findFlights"));
		findFlightsBt.click();
		WebElement departRaBt = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table[1]/tbody/tr[7]/td[1]/input"));
		departRaBt.click();
		WebElement returnRaBt = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table[2]/tbody/tr[7]/td[1]/input"));
		returnRaBt.click();
		WebElement continueBt = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/p/input"));
		continueBt.click();
		Thread.sleep(500);
		firstNameTb = driver.findElement(By.name("passFirst0"));
		firstNameTb.sendKeys(firstName);
		lastNameTb = driver.findElement(By.name("passLast0"));
		lastNameTb.sendKeys(lastName);
		WebElement lowCalDDB = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[4]/td/table/tbody/tr[2]/td[3]/select/option[6]"));
		lowCalDDB.click();
		WebElement cardTypeDDB = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[6]/td/table/tbody/tr[2]/td[1]/select/option[3]"));
		cardTypeDDB.click();
		WebElement creditNumberTb = driver.findElement(By.name("creditnumber"));
		creditNumberTb.sendKeys(cardNumber);
		WebElement expireMonthDDB = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[6]/td/table/tbody/tr[2]/td[3]/select[1]/option[9]"));
		expireMonthDDB.click();
		WebElement expireYearDDB = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[6]/td/table/tbody/tr[2]/td[3]/select[2]/option[12]"));
		expireYearDDB.click();
		firstNameTb = driver.findElement(By.name("cc_frst_name"));
		firstNameTb.sendKeys(firstName);
		lastNameTb = driver.findElement(By.name("cc_last_name"));
		lastNameTb.sendKeys(lastName);
		address1Tb = driver.findElement(By.name("billAddress1"));
		address1Tb.sendKeys(address1);
		address2Tb = driver.findElement(By.name("billAddress2"));
		address2Tb.sendKeys(address2);
		cityTb = driver.findElement(By.name("billCity")); 
		cityTb.sendKeys(city);
		stateTb = driver.findElement(By.name("billState"));
		stateTb.sendKeys(state);
		postalCodeTb = driver.findElement(By.name("billZip"));
		postalCodeTb.sendKeys(postCode);
		WebElement sameAsBillingTkB = driver.findElement(By.xpath("/html/body/div/table/tbody/tr/td[2]/table/tbody/tr[4]/td/table/tbody/tr/td[2]/table/tbody/tr[5]/td/form/table/tbody/tr[14]/td[2]/input"));
		sameAsBillingTkB.click();
		Thread.sleep(500);
		WebElement buyFlightsBt = driver.findElement(By.name("buyFlights"));
		buyFlightsBt.click();
		Thread.sleep(500);
		driver.close();
		driver.quit();
	}
}
